AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'lib/tasks/temporary/*.rake'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*.rake'
    - 'docs/tasks/*.rake'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*'

Rails/ReversibleMigration:
  Enabled: false
