AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'lib/tasks/temporary/*.rake'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*.rake'
    - 'docs/tasks/*.rake'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/UncommunicativeMethodParamName:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
