version: 2

jobs:
  build-and-test:
    working_directory: ~/bearden
    docker:
      - image: artsy/ruby:2.5.1-node-chrome
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:10.1-alpine
      - image: circleci/elasticsearch
    steps:
      - run:
          name: Install ICU for charlock_holmes
          command: apt-get install libicu-dev
      - checkout
      - restore_cache:
          key: bearden-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bearden-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Poll for Elasticsearch
          command: sleep 10 && curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200/
      - run:
          name: Setup database
          command: mv config/database{.circle,}.yml && bundle exec rake db:create db:migrate
      - run:
          name: Run tests
          command: bundle exec rake

  deploy-staging:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to staging
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/bearden-staging.git master

  deploy-production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/bearden-production.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: release
      - deploy-staging:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-production:
          filters:
            branches:
              only: release
